-- Catalogue de demonstration (les 20 morceaux).
-- A rejouer APRES schema.sql, sur une base neuve :
--     mysql -u root -p spotifree < backend/scripts/seed-musics.sql
--
-- Ne contient QUE les metadonnees des morceaux. Aucun utilisateur, aucun like,
-- aucune visite : ce sont des donnees personnelles, elles ne vont pas dans Git.
--
-- Les fichiers audio et les pochettes eux-memes vivent dans backend/public/, qui est
-- gitignore (poids). Sans eux, les morceaux s'affichent mais ne se lisent pas.

INSERT INTO `musics` (`id_music`, `title`, `artist`, `genre`, `src_image`, `src_audio`, `duration`, `play_count`) VALUES (1,'Blinding Lights','The Weeknd','Pop','images/1.jpg','musiques/atlasaudio-sentimental-piano.mp3',109,5),(2,'Numb','Linkin Park','Rock','images/2.jpg','musiques/bombinsound-stomp-and-claps.mp3',88,1),(3,'Lose Yourself','Eminem','Rap','images/3.jpg','musiques/jonasblakewood-energetic.mp3',152,3),(4,'Get Lucky','Daft Punk','Electro','images/4.jpg','musiques/the_mountain-phonk-phonk-music.mp3',103,1),(5,'Bohemian Rhapsody','Queen','Rock','images/5.jpg','musiques/the_mountain-success.mp3',104,5),(6,'Shape of You','Ed Sheeran','Pop','images/1.jpg','musiques/atlasaudio-sentimental-piano.mp3',109,0),(7,'Billie Jean','Michael Jackson','Pop','images/2.jpg','musiques/bombinsound-stomp-and-claps.mp3',88,2),(8,'Smells Like Teen Spirit','Nirvana','Grunge','images/3.jpg','musiques/jonasblakewood-energetic.mp3',152,0),(9,'One More Time','Daft Punk','Electro','images/4.jpg','musiques/the_mountain-phonk-phonk-music.mp3',103,0),(10,'Without Me','Eminem','Rap','images/5.jpg','musiques/the_mountain-success.mp3',104,0),(11,'Bad Guy','Billie Eilish','Pop','images/1.jpg','musiques/atlasaudio-sentimental-piano.mp3',109,3),(12,'Thunderstruck','AC/DC','Rock','images/2.jpg','musiques/bombinsound-stomp-and-claps.mp3',88,0),(13,'Starboy','The Weeknd','Pop','images/3.jpg','musiques/jonasblakewood-energetic.mp3',152,0),(14,'Around the World','Daft Punk','Electro','images/4.jpg','musiques/the_mountain-phonk-phonk-music.mp3',103,5),(15,'In the End','Linkin Park','Rock','images/5.jpg','musiques/the_mountain-success.mp3',104,0),(16,'Godzilla','Eminem','Rap','images/1.jpg','musiques/atlasaudio-sentimental-piano.mp3',109,0),(17,'Levitating','Dua Lipa','Pop','images/2.jpg','musiques/bombinsound-stomp-and-claps.mp3',88,0),(18,'Seven Nation Army','The White Stripes','Rock','images/3.jpg','musiques/jonasblakewood-energetic.mp3',152,0),(19,'Harder Better Faster Stronger','Daft Punk','Electro','images/4.jpg','musiques/the_mountain-phonk-phonk-music.mp3',103,0),(20,'Believer','Imagine Dragons','Pop Rock','images/5.jpg','musiques/the_mountain-success.mp3',104,14);
